/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.helloworld;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.ActivitiesClient;
import com.amazonaws.services.simpleworkflow.flow.ActivitySchedulingOptions;

/**
 * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.helloworld.HelloWorldActivities}. 
 * Used to invoke activities asynchronously from workflow code.
 */
public interface HelloWorldActivitiesClient extends ActivitiesClient
{

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.helloworld.HelloWorldActivities#printHello}
     */
    Promise<Void> printHello(String name);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.helloworld.HelloWorldActivities#printHello}
     */
    Promise<Void> printHello(String name, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.helloworld.HelloWorldActivities#printHello}
     */
    Promise<Void> printHello(String name, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.helloworld.HelloWorldActivities#printHello}
     */
    Promise<Void> printHello(Promise<String> name);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.helloworld.HelloWorldActivities#printHello}
     */
    Promise<Void> printHello(Promise<String> name, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.helloworld.HelloWorldActivities#printHello}
     */
    Promise<Void> printHello(Promise<String> name, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

}