/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry;

import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowClientExternal;

/**
 * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflow}. 
 * Used to start workflow executions or send signals from outside of the scope of a workflow.
 * Created through {@link CronWithRetryWorkflowClientExternalFactory#getClient}.
 * <p>
 * When starting child workflow from a parent workflow use {@link CronWithRetryWorkflowClient} instead.
 */
public interface CronWithRetryWorkflowClientExternal extends WorkflowClientExternal
{

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflow#startCron}
     */
    void startCron(com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflowOptions options);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflow#startCron}
     */
    void startCron(com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflowOptions options, StartWorkflowOptions optionsOverride);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflow#getInvocationHistory}
     */
    String getInvocationHistory() ;
}