/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowClient;

/**
 * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflow}. 
 * Used to invoke child workflows asynchronously from parent workflow code.
 * Created through {@link CronWithRetryWorkflowClientFactory#getClient}.
 * <p>
 * When running outside of the scope of a workflow use {@link CronWithRetryWorkflowClientExternal} instead.
 */
public interface CronWithRetryWorkflowClient extends WorkflowClient
{

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflow#startCron}
     */
    Promise<Void> startCron(com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflowOptions options);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflow#startCron}
     */
    Promise<Void> startCron(com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflowOptions options, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflow#startCron}
     */
    Promise<Void> startCron(com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflowOptions options, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflow#startCron}
     */
    Promise<Void> startCron(Promise<com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflowOptions> options);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflow#startCron}
     */
    Promise<Void> startCron(Promise<com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflowOptions> options, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflow#startCron}
     */
    Promise<Void> startCron(Promise<com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflowOptions> options, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);

}