/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry;

import com.amazonaws.services.simpleworkflow.flow.DataConverter;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowClientBase;
import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.generic.GenericWorkflowClient;
import com.amazonaws.services.simpleworkflow.model.WorkflowExecution;
import com.amazonaws.services.simpleworkflow.model.WorkflowType;

class CronWithRetryWorkflowClientImpl extends WorkflowClientBase implements CronWithRetryWorkflowClient {

    public CronWithRetryWorkflowClientImpl(WorkflowExecution workflowExecution, WorkflowType workflowType,  
            StartWorkflowOptions options, DataConverter dataConverter, GenericWorkflowClient genericClient) {
        super(workflowExecution, workflowType, options, dataConverter, genericClient);
    }
    
    @Override
    public final Promise<Void> startCron(com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflowOptions options) { 
        return startCron(Promise.asPromise(options), (StartWorkflowOptions)null);
    }
    
    @Override
    public final Promise<Void> startCron(com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflowOptions options, Promise<?>... waitFor) {
        return startCron(Promise.asPromise(options), (StartWorkflowOptions)null, waitFor);
    }
    
    
    @Override
    
    public final Promise<Void> startCron(com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflowOptions options, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        return startCron(Promise.asPromise(options), optionsOverride, waitFor);
    }

    @Override
    public final Promise<Void> startCron(Promise<com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflowOptions> options) {
        return startCron(options, (StartWorkflowOptions)null);
    }

    @Override
    public final Promise<Void> startCron(Promise<com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflowOptions> options, Promise<?>... waitFor) {
        return startCron(options, (StartWorkflowOptions)null, waitFor);
    }

    @Override
    
    @SuppressWarnings({ "unchecked", "rawtypes" })
    public final Promise<Void> startCron(Promise<com.amazonaws.services.simpleworkflow.flow.examples.cronwithretry.CronWithRetryWorkflowOptions> options, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        Promise[] _input_ = new Promise[1];
        _input_[0] = options;
        return (Promise) startWorkflowExecution(_input_, optionsOverride, Void.class, waitFor);
    }
    	

}