/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.booking;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowClient;

/**
 * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingWorkflow}. 
 * Used to invoke child workflows asynchronously from parent workflow code.
 * Created through {@link BookingWorkflowClientFactory#getClient}.
 * <p>
 * When running outside of the scope of a workflow use {@link BookingWorkflowClientExternal} instead.
 */
public interface BookingWorkflowClient extends WorkflowClient
{

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingWorkflow#makeBooking}
     */
    Promise<Void> makeBooking(int requestID, int customerID, boolean reserveAir, boolean reserveCar);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingWorkflow#makeBooking}
     */
    Promise<Void> makeBooking(int requestID, int customerID, boolean reserveAir, boolean reserveCar, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingWorkflow#makeBooking}
     */
    Promise<Void> makeBooking(int requestID, int customerID, boolean reserveAir, boolean reserveCar, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingWorkflow#makeBooking}
     */
    Promise<Void> makeBooking(Promise<Integer> requestID, Promise<Integer> customerID, Promise<Boolean> reserveAir, Promise<Boolean> reserveCar);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingWorkflow#makeBooking}
     */
    Promise<Void> makeBooking(Promise<Integer> requestID, Promise<Integer> customerID, Promise<Boolean> reserveAir, Promise<Boolean> reserveCar, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingWorkflow#makeBooking}
     */
    Promise<Void> makeBooking(Promise<Integer> requestID, Promise<Integer> customerID, Promise<Boolean> reserveAir, Promise<Boolean> reserveCar, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);

}