/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.booking;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.ActivitiesClient;
import com.amazonaws.services.simpleworkflow.flow.ActivitySchedulingOptions;

/**
 * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities}. 
 * Used to invoke activities asynchronously from workflow code.
 */
public interface BookingActivitiesClient extends ActivitiesClient
{

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#reserveCar}
     */
    Promise<Void> reserveCar(int requestId);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#reserveCar}
     */
    Promise<Void> reserveCar(int requestId, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#reserveCar}
     */
    Promise<Void> reserveCar(int requestId, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#reserveCar}
     */
    Promise<Void> reserveCar(Promise<Integer> requestId);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#reserveCar}
     */
    Promise<Void> reserveCar(Promise<Integer> requestId, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#reserveCar}
     */
    Promise<Void> reserveCar(Promise<Integer> requestId, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#reserveAirline}
     */
    Promise<Void> reserveAirline(int requestId);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#reserveAirline}
     */
    Promise<Void> reserveAirline(int requestId, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#reserveAirline}
     */
    Promise<Void> reserveAirline(int requestId, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#reserveAirline}
     */
    Promise<Void> reserveAirline(Promise<Integer> requestId);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#reserveAirline}
     */
    Promise<Void> reserveAirline(Promise<Integer> requestId, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#reserveAirline}
     */
    Promise<Void> reserveAirline(Promise<Integer> requestId, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#sendConfirmationActivity}
     */
    Promise<Void> sendConfirmationActivity(int customerId);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#sendConfirmationActivity}
     */
    Promise<Void> sendConfirmationActivity(int customerId, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#sendConfirmationActivity}
     */
    Promise<Void> sendConfirmationActivity(int customerId, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#sendConfirmationActivity}
     */
    Promise<Void> sendConfirmationActivity(Promise<Integer> customerId);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#sendConfirmationActivity}
     */
    Promise<Void> sendConfirmationActivity(Promise<Integer> customerId, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.booking.BookingActivities#sendConfirmationActivity}
     */
    Promise<Void> sendConfirmationActivity(Promise<Integer> customerId, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

}