/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.deployment;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.ActivitiesClient;
import com.amazonaws.services.simpleworkflow.flow.ActivitySchedulingOptions;

/**
 * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities}. 
 * Used to invoke activities asynchronously from workflow code.
 */
public interface DeploymentActivitiesClient extends ActivitiesClient
{

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployDatabase}
     */
    Promise<String> deployDatabase();

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployDatabase}
     */
    Promise<String> deployDatabase(Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployDatabase}
     */
    Promise<String> deployDatabase(ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployAppServer}
     */
    Promise<String> deployAppServer(java.util.List<java.lang.String> dataSources);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployAppServer}
     */
    Promise<String> deployAppServer(java.util.List<java.lang.String> dataSources, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployAppServer}
     */
    Promise<String> deployAppServer(java.util.List<java.lang.String> dataSources, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployAppServer}
     */
    Promise<String> deployAppServer(Promise<java.util.List<java.lang.String>> dataSources);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployAppServer}
     */
    Promise<String> deployAppServer(Promise<java.util.List<java.lang.String>> dataSources, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployAppServer}
     */
    Promise<String> deployAppServer(Promise<java.util.List<java.lang.String>> dataSources, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployWebServer}
     */
    Promise<String> deployWebServer(java.util.List<java.lang.String> appServerUrls, java.util.List<java.lang.String> dataSources);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployWebServer}
     */
    Promise<String> deployWebServer(java.util.List<java.lang.String> appServerUrls, java.util.List<java.lang.String> dataSources, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployWebServer}
     */
    Promise<String> deployWebServer(java.util.List<java.lang.String> appServerUrls, java.util.List<java.lang.String> dataSources, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployWebServer}
     */
    Promise<String> deployWebServer(Promise<java.util.List<java.lang.String>> appServerUrls, Promise<java.util.List<java.lang.String>> dataSources);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployWebServer}
     */
    Promise<String> deployWebServer(Promise<java.util.List<java.lang.String>> appServerUrls, Promise<java.util.List<java.lang.String>> dataSources, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployWebServer}
     */
    Promise<String> deployWebServer(Promise<java.util.List<java.lang.String>> appServerUrls, Promise<java.util.List<java.lang.String>> dataSources, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployLoadBalancer}
     */
    Promise<String> deployLoadBalancer(java.util.List<java.lang.String> frontendUrls);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployLoadBalancer}
     */
    Promise<String> deployLoadBalancer(java.util.List<java.lang.String> frontendUrls, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployLoadBalancer}
     */
    Promise<String> deployLoadBalancer(java.util.List<java.lang.String> frontendUrls, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployLoadBalancer}
     */
    Promise<String> deployLoadBalancer(Promise<java.util.List<java.lang.String>> frontendUrls);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployLoadBalancer}
     */
    Promise<String> deployLoadBalancer(Promise<java.util.List<java.lang.String>> frontendUrls, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentActivities#deployLoadBalancer}
     */
    Promise<String> deployLoadBalancer(Promise<java.util.List<java.lang.String>> frontendUrls, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

}