/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.deployment;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowSelfClient;

/**
 * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentWorkflow}. 
 * Used to continue a workflow execution as a new run.
 * Must be used from a worklfow scope. 
 */
public interface DeploymentWorkflowSelfClient extends WorkflowSelfClient
{

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentWorkflow#deploy}
     */
    void deploy(String springTemplate);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentWorkflow#deploy}
     */
    void deploy(String springTemplate, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentWorkflow#deploy}
     */
    void deploy(String springTemplate, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentWorkflow#deploy}
     */
    void deploy(Promise<String> springTemplate);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentWorkflow#deploy}
     */
    void deploy(Promise<String> springTemplate, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentWorkflow#deploy}
     */
    void deploy(Promise<String> springTemplate, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);
}