/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.deployment;

import com.amazonaws.services.simpleworkflow.flow.DataConverter;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowClientBase;
import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.generic.GenericWorkflowClient;
import com.amazonaws.services.simpleworkflow.model.WorkflowExecution;
import com.amazonaws.services.simpleworkflow.model.WorkflowType;

class DeploymentWorkflowClientImpl extends WorkflowClientBase implements DeploymentWorkflowClient {

    public DeploymentWorkflowClientImpl(WorkflowExecution workflowExecution, WorkflowType workflowType,  
            StartWorkflowOptions options, DataConverter dataConverter, GenericWorkflowClient genericClient) {
        super(workflowExecution, workflowType, options, dataConverter, genericClient);
    }
    
    @Override
    public final Promise<String> deploy(String springTemplate) { 
        return deploy(Promise.asPromise(springTemplate), (StartWorkflowOptions)null);
    }
    
    @Override
    public final Promise<String> deploy(String springTemplate, Promise<?>... waitFor) {
        return deploy(Promise.asPromise(springTemplate), (StartWorkflowOptions)null, waitFor);
    }
    
    
    @Override
    
    public final Promise<String> deploy(String springTemplate, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        return deploy(Promise.asPromise(springTemplate), optionsOverride, waitFor);
    }

    @Override
    public final Promise<String> deploy(Promise<String> springTemplate) {
        return deploy(springTemplate, (StartWorkflowOptions)null);
    }

    @Override
    public final Promise<String> deploy(Promise<String> springTemplate, Promise<?>... waitFor) {
        return deploy(springTemplate, (StartWorkflowOptions)null, waitFor);
    }

    @Override
    
    @SuppressWarnings({ "unchecked", "rawtypes" })
    public final Promise<String> deploy(Promise<String> springTemplate, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        Promise[] _input_ = new Promise[1];
        _input_[0] = springTemplate;
        return (Promise) startWorkflowExecution(_input_, optionsOverride, String.class, waitFor);
    }
    	

}