/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.deployment;

import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowClientExternal;

/**
 * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentWorkflow}. 
 * Used to start workflow executions or send signals from outside of the scope of a workflow.
 * Created through {@link DeploymentWorkflowClientExternalFactory#getClient}.
 * <p>
 * When starting child workflow from a parent workflow use {@link DeploymentWorkflowClient} instead.
 */
public interface DeploymentWorkflowClientExternal extends WorkflowClientExternal
{

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentWorkflow#deploy}
     */
    void deploy(String springTemplate);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.deployment.DeploymentWorkflow#deploy}
     */
    void deploy(String springTemplate, StartWorkflowOptions optionsOverride);
}