/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.hellolambda;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowClient;

/**
 * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.hellolambda.HelloLambdaWorkflow}. 
 * Used to invoke child workflows asynchronously from parent workflow code.
 * Created through {@link HelloLambdaWorkflowClientFactory#getClient}.
 * <p>
 * When running outside of the scope of a workflow use {@link HelloLambdaWorkflowClientExternal} instead.
 */
public interface HelloLambdaWorkflowClient extends WorkflowClient
{

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.hellolambda.HelloLambdaWorkflow#helloWorld}
     */
    Promise<Void> helloWorld(String name);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.hellolambda.HelloLambdaWorkflow#helloWorld}
     */
    Promise<Void> helloWorld(String name, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.hellolambda.HelloLambdaWorkflow#helloWorld}
     */
    Promise<Void> helloWorld(String name, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.hellolambda.HelloLambdaWorkflow#helloWorld}
     */
    Promise<Void> helloWorld(Promise<String> name);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.hellolambda.HelloLambdaWorkflow#helloWorld}
     */
    Promise<Void> helloWorld(Promise<String> name, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.hellolambda.HelloLambdaWorkflow#helloWorld}
     */
    Promise<Void> helloWorld(Promise<String> name, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);

}