/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.hellolambda;

import com.amazonaws.services.simpleworkflow.flow.core.AndPromise;
import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.core.Task;
import com.amazonaws.services.simpleworkflow.flow.DataConverter;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowSelfClientBase;
import com.amazonaws.services.simpleworkflow.flow.generic.ContinueAsNewWorkflowExecutionParameters;
import com.amazonaws.services.simpleworkflow.flow.generic.GenericWorkflowClient;

public class HelloLambdaWorkflowSelfClientImpl extends WorkflowSelfClientBase implements HelloLambdaWorkflowSelfClient {

    public HelloLambdaWorkflowSelfClientImpl() {
        this(null, new com.amazonaws.services.simpleworkflow.flow.JsonDataConverter(), null);
    }

    public HelloLambdaWorkflowSelfClientImpl(GenericWorkflowClient genericClient) {
        this(genericClient, new com.amazonaws.services.simpleworkflow.flow.JsonDataConverter(), null);
    }

    public HelloLambdaWorkflowSelfClientImpl(GenericWorkflowClient genericClient, 
            DataConverter dataConverter, StartWorkflowOptions schedulingOptions) {
            
        super(genericClient, dataConverter, schedulingOptions);
    }

    @Override
    public final void helloWorld(String name) { 
        helloWorldImpl(Promise.asPromise(name), (StartWorkflowOptions)null);
    }

    @Override
    public final void helloWorld(String name, Promise<?>... waitFor) { 
        helloWorldImpl(Promise.asPromise(name), (StartWorkflowOptions)null, waitFor);
    }
    
    @Override
    public final void helloWorld(String name, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        helloWorldImpl(Promise.asPromise(name), optionsOverride, waitFor);
    }
    
    @Override
    public final void helloWorld(Promise<String> name) {
        helloWorldImpl(name, (StartWorkflowOptions)null);
    }

    @Override
    public final void helloWorld(Promise<String> name, Promise<?>... waitFor) {
        helloWorldImpl(name, (StartWorkflowOptions)null, waitFor);
    }

    @Override
    public final void helloWorld(Promise<String> name, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        helloWorldImpl(name, optionsOverride, waitFor);
    }
    
    protected void helloWorldImpl(final Promise<String> name, final StartWorkflowOptions schedulingOptionsOverride, Promise<?>... waitFor) {
        new Task(new Promise[] { name, new AndPromise(waitFor) }) {
    		@Override
			protected void doExecute() throws Throwable {
                ContinueAsNewWorkflowExecutionParameters _parameters_ = new ContinueAsNewWorkflowExecutionParameters();
                Object[] _input_ = new Object[1];
                _input_[0] = name.get();
                String _stringInput_ = dataConverter.toData(_input_);
				_parameters_.setInput(_stringInput_);
				_parameters_ = _parameters_.createContinueAsNewParametersFromOptions(schedulingOptions, schedulingOptionsOverride);
                
                if (genericClient == null) {
                    genericClient = decisionContextProvider.getDecisionContext().getWorkflowClient();
                }
                genericClient.continueAsNewOnCompletion(_parameters_);
			}
		};
    }
}