/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowSelfClient;

/**
 * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingWorkflow}. 
 * Used to continue a workflow execution as a new run.
 * Must be used from a worklfow scope. 
 */
public interface FileProcessingWorkflowSelfClient extends WorkflowSelfClient
{

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingWorkflow#processFile}
     */
    void processFile(String sourceBucketName, String sourceFilename, String targetBucketName, String targetFilename);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingWorkflow#processFile}
     */
    void processFile(String sourceBucketName, String sourceFilename, String targetBucketName, String targetFilename, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingWorkflow#processFile}
     */
    void processFile(String sourceBucketName, String sourceFilename, String targetBucketName, String targetFilename, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingWorkflow#processFile}
     */
    void processFile(Promise<String> sourceBucketName, Promise<String> sourceFilename, Promise<String> targetBucketName, Promise<String> targetFilename);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingWorkflow#processFile}
     */
    void processFile(Promise<String> sourceBucketName, Promise<String> sourceFilename, Promise<String> targetBucketName, Promise<String> targetFilename, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingWorkflow#processFile}
     */
    void processFile(Promise<String> sourceBucketName, Promise<String> sourceFilename, Promise<String> targetBucketName, Promise<String> targetFilename, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);
}