/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing;

import com.amazonaws.services.simpleworkflow.flow.core.AndPromise;
import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.core.Task;
import com.amazonaws.services.simpleworkflow.flow.DataConverter;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowSelfClientBase;
import com.amazonaws.services.simpleworkflow.flow.generic.ContinueAsNewWorkflowExecutionParameters;
import com.amazonaws.services.simpleworkflow.flow.generic.GenericWorkflowClient;

public class FileProcessingWorkflowSelfClientImpl extends WorkflowSelfClientBase implements FileProcessingWorkflowSelfClient {

    public FileProcessingWorkflowSelfClientImpl() {
        this(null, new com.amazonaws.services.simpleworkflow.flow.JsonDataConverter(), null);
    }

    public FileProcessingWorkflowSelfClientImpl(GenericWorkflowClient genericClient) {
        this(genericClient, new com.amazonaws.services.simpleworkflow.flow.JsonDataConverter(), null);
    }

    public FileProcessingWorkflowSelfClientImpl(GenericWorkflowClient genericClient, 
            DataConverter dataConverter, StartWorkflowOptions schedulingOptions) {
            
        super(genericClient, dataConverter, schedulingOptions);
    }

    @Override
    public final void processFile(String sourceBucketName, String sourceFilename, String targetBucketName, String targetFilename) { 
        processFileImpl(Promise.asPromise(sourceBucketName), Promise.asPromise(sourceFilename), Promise.asPromise(targetBucketName), Promise.asPromise(targetFilename), (StartWorkflowOptions)null);
    }

    @Override
    public final void processFile(String sourceBucketName, String sourceFilename, String targetBucketName, String targetFilename, Promise<?>... waitFor) { 
        processFileImpl(Promise.asPromise(sourceBucketName), Promise.asPromise(sourceFilename), Promise.asPromise(targetBucketName), Promise.asPromise(targetFilename), (StartWorkflowOptions)null, waitFor);
    }
    
    @Override
    public final void processFile(String sourceBucketName, String sourceFilename, String targetBucketName, String targetFilename, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        processFileImpl(Promise.asPromise(sourceBucketName), Promise.asPromise(sourceFilename), Promise.asPromise(targetBucketName), Promise.asPromise(targetFilename), optionsOverride, waitFor);
    }
    
    @Override
    public final void processFile(Promise<String> sourceBucketName, Promise<String> sourceFilename, Promise<String> targetBucketName, Promise<String> targetFilename) {
        processFileImpl(sourceBucketName, sourceFilename, targetBucketName, targetFilename, (StartWorkflowOptions)null);
    }

    @Override
    public final void processFile(Promise<String> sourceBucketName, Promise<String> sourceFilename, Promise<String> targetBucketName, Promise<String> targetFilename, Promise<?>... waitFor) {
        processFileImpl(sourceBucketName, sourceFilename, targetBucketName, targetFilename, (StartWorkflowOptions)null, waitFor);
    }

    @Override
    public final void processFile(Promise<String> sourceBucketName, Promise<String> sourceFilename, Promise<String> targetBucketName, Promise<String> targetFilename, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        processFileImpl(sourceBucketName, sourceFilename, targetBucketName, targetFilename, optionsOverride, waitFor);
    }
    
    protected void processFileImpl(final Promise<String> sourceBucketName, final Promise<String> sourceFilename, final Promise<String> targetBucketName, final Promise<String> targetFilename, final StartWorkflowOptions schedulingOptionsOverride, Promise<?>... waitFor) {
        new Task(new Promise[] { sourceBucketName, sourceFilename, targetBucketName, targetFilename, new AndPromise(waitFor) }) {
    		@Override
			protected void doExecute() throws Throwable {
                ContinueAsNewWorkflowExecutionParameters _parameters_ = new ContinueAsNewWorkflowExecutionParameters();
                Object[] _input_ = new Object[4];
                _input_[0] = sourceBucketName.get();
                _input_[1] = sourceFilename.get();
                _input_[2] = targetBucketName.get();
                _input_[3] = targetFilename.get();
                String _stringInput_ = dataConverter.toData(_input_);
				_parameters_.setInput(_stringInput_);
				_parameters_ = _parameters_.createContinueAsNewParametersFromOptions(schedulingOptions, schedulingOptionsOverride);
                
                if (genericClient == null) {
                    genericClient = decisionContextProvider.getDecisionContext().getWorkflowClient();
                }
                genericClient.continueAsNewOnCompletion(_parameters_);
			}
		};
    }
}