/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.ActivitiesClient;
import com.amazonaws.services.simpleworkflow.flow.ActivitySchedulingOptions;

/**
 * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingActivities}. 
 * Used to invoke activities asynchronously from workflow code.
 */
public interface FileProcessingActivitiesClient extends ActivitiesClient
{

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingActivities#processFile}
     */
    Promise<Void> processFile(String inputFileName, String outputFileName);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingActivities#processFile}
     */
    Promise<Void> processFile(String inputFileName, String outputFileName, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingActivities#processFile}
     */
    Promise<Void> processFile(String inputFileName, String outputFileName, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingActivities#processFile}
     */
    Promise<Void> processFile(Promise<String> inputFileName, Promise<String> outputFileName);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingActivities#processFile}
     */
    Promise<Void> processFile(Promise<String> inputFileName, Promise<String> outputFileName, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingActivities#processFile}
     */
    Promise<Void> processFile(Promise<String> inputFileName, Promise<String> outputFileName, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

}