/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing;

import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowClientExternal;

/**
 * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingWorkflow}. 
 * Used to start workflow executions or send signals from outside of the scope of a workflow.
 * Created through {@link FileProcessingWorkflowClientExternalFactory#getClient}.
 * <p>
 * When starting child workflow from a parent workflow use {@link FileProcessingWorkflowClient} instead.
 */
public interface FileProcessingWorkflowClientExternal extends WorkflowClientExternal
{

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingWorkflow#processFile}
     */
    void processFile(String sourceBucketName, String sourceFilename, String targetBucketName, String targetFilename);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingWorkflow#processFile}
     */
    void processFile(String sourceBucketName, String sourceFilename, String targetBucketName, String targetFilename, StartWorkflowOptions optionsOverride);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.FileProcessingWorkflow#getState}
     */
    String getState() ;
}