/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.ActivitiesClient;
import com.amazonaws.services.simpleworkflow.flow.ActivitySchedulingOptions;

/**
 * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities}. 
 * Used to invoke activities asynchronously from workflow code.
 */
public interface SimpleStoreActivitiesClient extends ActivitiesClient
{

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#upload}
     */
    Promise<Void> upload(String bucketName, String localName, String targetName);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#upload}
     */
    Promise<Void> upload(String bucketName, String localName, String targetName, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#upload}
     */
    Promise<Void> upload(String bucketName, String localName, String targetName, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#upload}
     */
    Promise<Void> upload(Promise<String> bucketName, Promise<String> localName, Promise<String> targetName);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#upload}
     */
    Promise<Void> upload(Promise<String> bucketName, Promise<String> localName, Promise<String> targetName, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#upload}
     */
    Promise<Void> upload(Promise<String> bucketName, Promise<String> localName, Promise<String> targetName, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#download}
     */
    Promise<String> download(String bucketName, String remoteName, String localName);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#download}
     */
    Promise<String> download(String bucketName, String remoteName, String localName, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#download}
     */
    Promise<String> download(String bucketName, String remoteName, String localName, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#download}
     */
    Promise<String> download(Promise<String> bucketName, Promise<String> remoteName, Promise<String> localName);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#download}
     */
    Promise<String> download(Promise<String> bucketName, Promise<String> remoteName, Promise<String> localName, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#download}
     */
    Promise<String> download(Promise<String> bucketName, Promise<String> remoteName, Promise<String> localName, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#deleteLocalFile}
     */
    Promise<Void> deleteLocalFile(String fileName);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#deleteLocalFile}
     */
    Promise<Void> deleteLocalFile(String fileName, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#deleteLocalFile}
     */
    Promise<Void> deleteLocalFile(String fileName, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#deleteLocalFile}
     */
    Promise<Void> deleteLocalFile(Promise<String> fileName);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#deleteLocalFile}
     */
    Promise<Void> deleteLocalFile(Promise<String> fileName, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.fileprocessing.SimpleStoreActivities#deleteLocalFile}
     */
    Promise<Void> deleteLocalFile(Promise<String> fileName, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

}