/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.splitmerge;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowSelfClient;

/**
 * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorWorkflow}. 
 * Used to continue a workflow execution as a new run.
 * Must be used from a worklfow scope. 
 */
public interface AverageCalculatorWorkflowSelfClient extends WorkflowSelfClient
{

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorWorkflow#average}
     */
    void average(String bucketName, String fileName, int numberOfWorkers);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorWorkflow#average}
     */
    void average(String bucketName, String fileName, int numberOfWorkers, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorWorkflow#average}
     */
    void average(String bucketName, String fileName, int numberOfWorkers, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorWorkflow#average}
     */
    void average(Promise<String> bucketName, Promise<String> fileName, Promise<Integer> numberOfWorkers);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorWorkflow#average}
     */
    void average(Promise<String> bucketName, Promise<String> fileName, Promise<Integer> numberOfWorkers, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorWorkflow#average}
     */
    void average(Promise<String> bucketName, Promise<String> fileName, Promise<Integer> numberOfWorkers, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);
}