/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.splitmerge;

import com.amazonaws.services.simpleworkflow.flow.core.AndPromise;
import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.core.Task;
import com.amazonaws.services.simpleworkflow.flow.DataConverter;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowSelfClientBase;
import com.amazonaws.services.simpleworkflow.flow.generic.ContinueAsNewWorkflowExecutionParameters;
import com.amazonaws.services.simpleworkflow.flow.generic.GenericWorkflowClient;

public class AverageCalculatorWorkflowSelfClientImpl extends WorkflowSelfClientBase implements AverageCalculatorWorkflowSelfClient {

    public AverageCalculatorWorkflowSelfClientImpl() {
        this(null, new com.amazonaws.services.simpleworkflow.flow.JsonDataConverter(), null);
    }

    public AverageCalculatorWorkflowSelfClientImpl(GenericWorkflowClient genericClient) {
        this(genericClient, new com.amazonaws.services.simpleworkflow.flow.JsonDataConverter(), null);
    }

    public AverageCalculatorWorkflowSelfClientImpl(GenericWorkflowClient genericClient, 
            DataConverter dataConverter, StartWorkflowOptions schedulingOptions) {
            
        super(genericClient, dataConverter, schedulingOptions);
    }

    @Override
    public final void average(String bucketName, String fileName, int numberOfWorkers) { 
        averageImpl(Promise.asPromise(bucketName), Promise.asPromise(fileName), Promise.asPromise(numberOfWorkers), (StartWorkflowOptions)null);
    }

    @Override
    public final void average(String bucketName, String fileName, int numberOfWorkers, Promise<?>... waitFor) { 
        averageImpl(Promise.asPromise(bucketName), Promise.asPromise(fileName), Promise.asPromise(numberOfWorkers), (StartWorkflowOptions)null, waitFor);
    }
    
    @Override
    public final void average(String bucketName, String fileName, int numberOfWorkers, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        averageImpl(Promise.asPromise(bucketName), Promise.asPromise(fileName), Promise.asPromise(numberOfWorkers), optionsOverride, waitFor);
    }
    
    @Override
    public final void average(Promise<String> bucketName, Promise<String> fileName, Promise<Integer> numberOfWorkers) {
        averageImpl(bucketName, fileName, numberOfWorkers, (StartWorkflowOptions)null);
    }

    @Override
    public final void average(Promise<String> bucketName, Promise<String> fileName, Promise<Integer> numberOfWorkers, Promise<?>... waitFor) {
        averageImpl(bucketName, fileName, numberOfWorkers, (StartWorkflowOptions)null, waitFor);
    }

    @Override
    public final void average(Promise<String> bucketName, Promise<String> fileName, Promise<Integer> numberOfWorkers, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        averageImpl(bucketName, fileName, numberOfWorkers, optionsOverride, waitFor);
    }
    
    protected void averageImpl(final Promise<String> bucketName, final Promise<String> fileName, final Promise<Integer> numberOfWorkers, final StartWorkflowOptions schedulingOptionsOverride, Promise<?>... waitFor) {
        new Task(new Promise[] { bucketName, fileName, numberOfWorkers, new AndPromise(waitFor) }) {
    		@Override
			protected void doExecute() throws Throwable {
                ContinueAsNewWorkflowExecutionParameters _parameters_ = new ContinueAsNewWorkflowExecutionParameters();
                Object[] _input_ = new Object[3];
                _input_[0] = bucketName.get();
                _input_[1] = fileName.get();
                _input_[2] = numberOfWorkers.get();
                String _stringInput_ = dataConverter.toData(_input_);
				_parameters_.setInput(_stringInput_);
				_parameters_ = _parameters_.createContinueAsNewParametersFromOptions(schedulingOptions, schedulingOptionsOverride);
                
                if (genericClient == null) {
                    genericClient = decisionContextProvider.getDecisionContext().getWorkflowClient();
                }
                genericClient.continueAsNewOnCompletion(_parameters_);
			}
		};
    }
}