/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.splitmerge;

import com.amazonaws.services.simpleworkflow.flow.DataConverter;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowClientBase;
import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.generic.GenericWorkflowClient;
import com.amazonaws.services.simpleworkflow.model.WorkflowExecution;
import com.amazonaws.services.simpleworkflow.model.WorkflowType;

class AverageCalculatorWorkflowClientImpl extends WorkflowClientBase implements AverageCalculatorWorkflowClient {

    public AverageCalculatorWorkflowClientImpl(WorkflowExecution workflowExecution, WorkflowType workflowType,  
            StartWorkflowOptions options, DataConverter dataConverter, GenericWorkflowClient genericClient) {
        super(workflowExecution, workflowType, options, dataConverter, genericClient);
    }
    
    @Override
    public final Promise<Void> average(String bucketName, String fileName, int numberOfWorkers) { 
        return average(Promise.asPromise(bucketName), Promise.asPromise(fileName), Promise.asPromise(numberOfWorkers), (StartWorkflowOptions)null);
    }
    
    @Override
    public final Promise<Void> average(String bucketName, String fileName, int numberOfWorkers, Promise<?>... waitFor) {
        return average(Promise.asPromise(bucketName), Promise.asPromise(fileName), Promise.asPromise(numberOfWorkers), (StartWorkflowOptions)null, waitFor);
    }
    
    
    @Override
    
    public final Promise<Void> average(String bucketName, String fileName, int numberOfWorkers, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        return average(Promise.asPromise(bucketName), Promise.asPromise(fileName), Promise.asPromise(numberOfWorkers), optionsOverride, waitFor);
    }

    @Override
    public final Promise<Void> average(Promise<String> bucketName, Promise<String> fileName, Promise<Integer> numberOfWorkers) {
        return average(bucketName, fileName, numberOfWorkers, (StartWorkflowOptions)null);
    }

    @Override
    public final Promise<Void> average(Promise<String> bucketName, Promise<String> fileName, Promise<Integer> numberOfWorkers, Promise<?>... waitFor) {
        return average(bucketName, fileName, numberOfWorkers, (StartWorkflowOptions)null, waitFor);
    }

    @Override
    
    @SuppressWarnings({ "unchecked", "rawtypes" })
    public final Promise<Void> average(Promise<String> bucketName, Promise<String> fileName, Promise<Integer> numberOfWorkers, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        Promise[] _input_ = new Promise[3];
        _input_[0] = bucketName;
        _input_[1] = fileName;
        _input_[2] = numberOfWorkers;
        return (Promise) startWorkflowExecution(_input_, optionsOverride, Void.class, waitFor);
    }
    	

}