/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.splitmerge;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.ActivitiesClient;
import com.amazonaws.services.simpleworkflow.flow.ActivitySchedulingOptions;

/**
 * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities}. 
 * Used to invoke activities asynchronously from workflow code.
 */
public interface AverageCalculatorActivitiesClient extends ActivitiesClient
{

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#computeDataSizeForInputData}
     */
    Promise<Integer> computeDataSizeForInputData(String bucketName, String filename);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#computeDataSizeForInputData}
     */
    Promise<Integer> computeDataSizeForInputData(String bucketName, String filename, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#computeDataSizeForInputData}
     */
    Promise<Integer> computeDataSizeForInputData(String bucketName, String filename, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#computeDataSizeForInputData}
     */
    Promise<Integer> computeDataSizeForInputData(Promise<String> bucketName, Promise<String> filename);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#computeDataSizeForInputData}
     */
    Promise<Integer> computeDataSizeForInputData(Promise<String> bucketName, Promise<String> filename, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#computeDataSizeForInputData}
     */
    Promise<Integer> computeDataSizeForInputData(Promise<String> bucketName, Promise<String> filename, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#computeSumForChunk}
     */
    Promise<Integer> computeSumForChunk(String bucketName, String filename, int chunkNumber, int chunkSize);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#computeSumForChunk}
     */
    Promise<Integer> computeSumForChunk(String bucketName, String filename, int chunkNumber, int chunkSize, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#computeSumForChunk}
     */
    Promise<Integer> computeSumForChunk(String bucketName, String filename, int chunkNumber, int chunkSize, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#computeSumForChunk}
     */
    Promise<Integer> computeSumForChunk(Promise<String> bucketName, Promise<String> filename, Promise<Integer> chunkNumber, Promise<Integer> chunkSize);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#computeSumForChunk}
     */
    Promise<Integer> computeSumForChunk(Promise<String> bucketName, Promise<String> filename, Promise<Integer> chunkNumber, Promise<Integer> chunkSize, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#computeSumForChunk}
     */
    Promise<Integer> computeSumForChunk(Promise<String> bucketName, Promise<String> filename, Promise<Integer> chunkNumber, Promise<Integer> chunkSize, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#reportResult}
     */
    Promise<Void> reportResult(double average);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#reportResult}
     */
    Promise<Void> reportResult(double average, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#reportResult}
     */
    Promise<Void> reportResult(double average, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#reportResult}
     */
    Promise<Void> reportResult(Promise<Double> average);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#reportResult}
     */
    Promise<Void> reportResult(Promise<Double> average, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.splitmerge.AverageCalculatorActivities#reportResult}
     */
    Promise<Void> reportResult(Promise<Double> average, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

}