/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.ActivitiesClient;
import com.amazonaws.services.simpleworkflow.flow.ActivitySchedulingOptions;

/**
 * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.ErrorReportingActivities}. 
 * Used to invoke activities asynchronously from workflow code.
 */
public interface ErrorReportingActivitiesClient extends ActivitiesClient
{

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.ErrorReportingActivities#reportFailure}
     */
    Promise<Void> reportFailure(Throwable e);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.ErrorReportingActivities#reportFailure}
     */
    Promise<Void> reportFailure(Throwable e, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.ErrorReportingActivities#reportFailure}
     */
    Promise<Void> reportFailure(Throwable e, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.ErrorReportingActivities#reportFailure}
     */
    Promise<Void> reportFailure(Promise<Throwable> e);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.ErrorReportingActivities#reportFailure}
     */
    Promise<Void> reportFailure(Promise<Throwable> e, Promise<?>... waitFor);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.ErrorReportingActivities#reportFailure}
     */
    Promise<Void> reportFailure(Promise<Throwable> e, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

}