/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow;

import com.amazonaws.services.simpleworkflow.flow.core.AndPromise;
import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.core.Task;
import com.amazonaws.services.simpleworkflow.flow.DataConverter;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowSelfClientBase;
import com.amazonaws.services.simpleworkflow.flow.generic.ContinueAsNewWorkflowExecutionParameters;
import com.amazonaws.services.simpleworkflow.flow.generic.GenericWorkflowClient;

public class PeriodicWorkflowSelfClientImpl extends WorkflowSelfClientBase implements PeriodicWorkflowSelfClient {

    public PeriodicWorkflowSelfClientImpl() {
        this(null, new com.amazonaws.services.simpleworkflow.flow.JsonDataConverter(), null);
    }

    public PeriodicWorkflowSelfClientImpl(GenericWorkflowClient genericClient) {
        this(genericClient, new com.amazonaws.services.simpleworkflow.flow.JsonDataConverter(), null);
    }

    public PeriodicWorkflowSelfClientImpl(GenericWorkflowClient genericClient, 
            DataConverter dataConverter, StartWorkflowOptions schedulingOptions) {
            
        super(genericClient, dataConverter, schedulingOptions);
    }

    @Override
    public final void startPeriodicWorkflow(com.amazonaws.services.simpleworkflow.model.ActivityType activity, Object[] activityArguments, com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.PeriodicWorkflowOptions options) { 
        startPeriodicWorkflowImpl(Promise.asPromise(activity), Promise.asPromise(activityArguments), Promise.asPromise(options), (StartWorkflowOptions)null);
    }

    @Override
    public final void startPeriodicWorkflow(com.amazonaws.services.simpleworkflow.model.ActivityType activity, Object[] activityArguments, com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.PeriodicWorkflowOptions options, Promise<?>... waitFor) { 
        startPeriodicWorkflowImpl(Promise.asPromise(activity), Promise.asPromise(activityArguments), Promise.asPromise(options), (StartWorkflowOptions)null, waitFor);
    }
    
    @Override
    public final void startPeriodicWorkflow(com.amazonaws.services.simpleworkflow.model.ActivityType activity, Object[] activityArguments, com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.PeriodicWorkflowOptions options, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        startPeriodicWorkflowImpl(Promise.asPromise(activity), Promise.asPromise(activityArguments), Promise.asPromise(options), optionsOverride, waitFor);
    }
    
    @Override
    public final void startPeriodicWorkflow(Promise<com.amazonaws.services.simpleworkflow.model.ActivityType> activity, Promise<Object[]> activityArguments, Promise<com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.PeriodicWorkflowOptions> options) {
        startPeriodicWorkflowImpl(activity, activityArguments, options, (StartWorkflowOptions)null);
    }

    @Override
    public final void startPeriodicWorkflow(Promise<com.amazonaws.services.simpleworkflow.model.ActivityType> activity, Promise<Object[]> activityArguments, Promise<com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.PeriodicWorkflowOptions> options, Promise<?>... waitFor) {
        startPeriodicWorkflowImpl(activity, activityArguments, options, (StartWorkflowOptions)null, waitFor);
    }

    @Override
    public final void startPeriodicWorkflow(Promise<com.amazonaws.services.simpleworkflow.model.ActivityType> activity, Promise<Object[]> activityArguments, Promise<com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.PeriodicWorkflowOptions> options, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        startPeriodicWorkflowImpl(activity, activityArguments, options, optionsOverride, waitFor);
    }
    
    protected void startPeriodicWorkflowImpl(final Promise<com.amazonaws.services.simpleworkflow.model.ActivityType> activity, final Promise<Object[]> activityArguments, final Promise<com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.PeriodicWorkflowOptions> options, final StartWorkflowOptions schedulingOptionsOverride, Promise<?>... waitFor) {
        new Task(new Promise[] { activity, activityArguments, options, new AndPromise(waitFor) }) {
    		@Override
			protected void doExecute() throws Throwable {
                ContinueAsNewWorkflowExecutionParameters _parameters_ = new ContinueAsNewWorkflowExecutionParameters();
                Object[] _input_ = new Object[3];
                _input_[0] = activity.get();
                _input_[1] = activityArguments.get();
                _input_[2] = options.get();
                String _stringInput_ = dataConverter.toData(_input_);
				_parameters_.setInput(_stringInput_);
				_parameters_ = _parameters_.createContinueAsNewParametersFromOptions(schedulingOptions, schedulingOptionsOverride);
                
                if (genericClient == null) {
                    genericClient = decisionContextProvider.getDecisionContext().getWorkflowClient();
                }
                genericClient.continueAsNewOnCompletion(_parameters_);
			}
		};
    }
}