/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow;

import com.amazonaws.services.simpleworkflow.flow.ActivitiesClientBase;
import com.amazonaws.services.simpleworkflow.flow.ActivitySchedulingOptions;
import com.amazonaws.services.simpleworkflow.flow.DataConverter;
import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.generic.GenericActivityClient;
import com.amazonaws.services.simpleworkflow.model.ActivityType;

public class PeriodicWorkflowActivitiesClientImpl extends ActivitiesClientBase implements PeriodicWorkflowActivitiesClient {

	public PeriodicWorkflowActivitiesClientImpl() {
        this(null, new com.amazonaws.services.simpleworkflow.flow.JsonDataConverter(), null);
    }

    public PeriodicWorkflowActivitiesClientImpl(GenericActivityClient genericClient) {
        this(genericClient, new com.amazonaws.services.simpleworkflow.flow.JsonDataConverter(), null);
    }
    
    public PeriodicWorkflowActivitiesClientImpl(GenericActivityClient genericClient, 
            DataConverter dataConverter, ActivitySchedulingOptions schedulingOptions) {
            
        super(genericClient, dataConverter, schedulingOptions);
    }
    
    @Override
    public final Promise<Void> doSomeWork(String parameter) {
        return doSomeWorkImpl(Promise.asPromise(parameter), (ActivitySchedulingOptions)null);
    }

    @Override
    public final Promise<Void> doSomeWork(String parameter, Promise<?>... waitFor) {
        return doSomeWorkImpl(Promise.asPromise(parameter), (ActivitySchedulingOptions)null, waitFor);
    }

    @Override
    public final Promise<Void> doSomeWork(String parameter, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor) {
        return doSomeWorkImpl(Promise.asPromise(parameter), optionsOverride, waitFor);
    }

    @Override
    public final Promise<Void> doSomeWork(Promise<String> parameter) {
        return doSomeWorkImpl(parameter, (ActivitySchedulingOptions)null);
    }

    @Override
    public final Promise<Void> doSomeWork(Promise<String> parameter, Promise<?>... waitFor) {
        return doSomeWorkImpl(parameter, (ActivitySchedulingOptions)null, waitFor);
    }

    @Override
    public final Promise<Void> doSomeWork(Promise<String> parameter, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor) {
        return doSomeWorkImpl(parameter, optionsOverride, waitFor);
    }
    
    
    @SuppressWarnings({ "unchecked", "rawtypes" })
    protected Promise<Void> doSomeWorkImpl(final Promise<String> parameter, final ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor) {

        ActivityType _activityType = new ActivityType();
		_activityType.setName("PeriodicWorkflowActivities.doSomeWork");
		_activityType.setVersion("1.0");

        Promise[] _input_ = new Promise[1];
        _input_[0] = parameter;

        return (Promise)scheduleActivity(_activityType, _input_, optionsOverride, Void.class, waitFor);
    }

}