/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow;

import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowClientExternal;

/**
 * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.PeriodicWorkflow}. 
 * Used to start workflow executions or send signals from outside of the scope of a workflow.
 * Created through {@link PeriodicWorkflowClientExternalFactory#getClient}.
 * <p>
 * When starting child workflow from a parent workflow use {@link PeriodicWorkflowClient} instead.
 */
public interface PeriodicWorkflowClientExternal extends WorkflowClientExternal
{

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.PeriodicWorkflow#startPeriodicWorkflow}
     */
    void startPeriodicWorkflow(com.amazonaws.services.simpleworkflow.model.ActivityType activity, Object[] activityArguments, com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.PeriodicWorkflowOptions options);

    /**
     * Generated from {@link com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.PeriodicWorkflow#startPeriodicWorkflow}
     */
    void startPeriodicWorkflow(com.amazonaws.services.simpleworkflow.model.ActivityType activity, Object[] activityArguments, com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.PeriodicWorkflowOptions options, StartWorkflowOptions optionsOverride);
}