// Generated by nex-gen. DO NOT EDIT.
package io.temporal.samples.nexuswalkthrough.generatedservice;

import io.nexusrpc.Operation;
import io.nexusrpc.Service;

/** Start a purchase approval, message it while it is pending, and learn the outcome. */
@Service(name = "temporal.samples.approval.v1.ApprovalService")
public interface ApprovalService {
  /** Report whether a purchase needs approval, before any durable work starts. */
  @Operation(name = "CheckApprovalRequired")
  CheckApprovalRequiredOutput checkApprovalRequired(CheckApprovalRequiredInput input);

  /** Start an approval and return the decision once it is made. */
  @Operation(name = "RequestApproval")
  RequestApprovalOutput requestApproval(RequestApprovalInput input);

  /** Ask the approver again. Returns nothing. */
  @Operation(name = "RemindApprover")
  void remindApprover(RemindApproverInput input);

  /** Supply the decision and confirm it was recorded. */
  @Operation(name = "SubmitDecision")
  SubmitDecisionOutput submitDecision(SubmitDecisionInput input);

  /** Attach supporting information to a purchase, whether or not its approval exists yet. */
  @Operation(name = "AttachApprovalContext")
  void attachApprovalContext(AttachApprovalContextInput input);

  /** Notify the requester once the decision is final. */
  @Operation(name = "NotifyRequester")
  NotifyRequesterOutput notifyRequester(NotifyRequesterInput input);
}
