// Generated by nex-gen. DO NOT EDIT.
package io.temporal.samples.nexuswalkthrough.generatedservice;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

@JsonSerialize(using = AttachApprovalContextInput.Serializer.class)
@JsonDeserialize(using = AttachApprovalContextInput.Deserializer.class)
public final class AttachApprovalContextInput {
  private final String itemId;
  private final String requester;
  private final double amount;

  /** The supporting information to attach. */
  private final String note;

  public AttachApprovalContextInput(String itemId, String requester, double amount, String note) {
    this.itemId = itemId;
    this.requester = requester;
    this.amount = amount;
    this.note = note;
  }

  public String getItemId() {
    return itemId;
  }

  public String getRequester() {
    return requester;
  }

  public double getAmount() {
    return amount;
  }

  public String getNote() {
    return note;
  }

  @Override
  public boolean equals(@Nullable Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof AttachApprovalContextInput)) {
      return false;
    }
    AttachApprovalContextInput that = (AttachApprovalContextInput) other;
    return Objects.equals(this.itemId, that.itemId)
        && Objects.equals(this.requester, that.requester)
        && this.amount == that.amount
        && Objects.equals(this.note, that.note);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemId, requester, amount, note);
  }

  @Override
  public String toString() {
    return "AttachApprovalContextInput{"
        + "itemId="
        + itemId
        + ", requester="
        + requester
        + ", amount="
        + amount
        + ", note="
        + note
        + "}";
  }

  public static final class Serializer
      extends com.fasterxml.jackson.databind.JsonSerializer<AttachApprovalContextInput> {
    @Override
    public void serialize(
        AttachApprovalContextInput value, JsonGenerator gen, SerializerProvider serializers)
        throws IOException {
      gen.writeStartObject();
      if (value.itemId != null) {
        gen.writeStringField("itemId", value.itemId);
      }
      if (value.requester != null) {
        gen.writeStringField("requester", value.requester);
      }
      gen.writeNumberField("amount", value.amount);

      if (value.note != null) {
        gen.writeStringField("note", value.note);
      }
      gen.writeEndObject();
    }
  }

  public static final class Deserializer
      extends com.fasterxml.jackson.databind.JsonDeserializer<AttachApprovalContextInput> {
    @Override
    public AttachApprovalContextInput deserialize(JsonParser parser, DeserializationContext context)
        throws IOException {
      JsonNode node = parser.readValueAsTree();
      List<Violation> violations = new ArrayList<>();
      if (node == null || !node.isObject()) {
        violations.add(new Violation("", "expected object"));
        throw new ValidationException(violations);
      }
      Iterator<String> fieldNames = node.fieldNames();
      while (fieldNames.hasNext()) {
        String key = fieldNames.next();
        switch (key) {
          case "amount":
          case "itemId":
          case "note":
          case "requester":
            break;
          default:
            violations.add(new Violation(key, "unknown field"));
        }
      }
      String itemId = null;
      {
        JsonNode field = node.get("itemId");
        if (field == null) {
          violations.add(new Violation("itemId", "required"));
        } else if (field.isNull()) {
          violations.add(new Violation("itemId", "explicit null not allowed"));
        } else {
          if (!field.isTextual()) {
            violations.add(new Violation("itemId", "expected string"));
          } else {
            itemId = field.textValue();
          }
        }
      }
      String requester = null;
      {
        JsonNode field = node.get("requester");
        if (field == null) {
          violations.add(new Violation("requester", "required"));
        } else if (field.isNull()) {
          violations.add(new Violation("requester", "explicit null not allowed"));
        } else {
          if (!field.isTextual()) {
            violations.add(new Violation("requester", "expected string"));
          } else {
            requester = field.textValue();
          }
        }
      }
      double amount = 0.0;
      {
        JsonNode field = node.get("amount");
        if (field == null) {
          violations.add(new Violation("amount", "required"));
        } else if (field.isNull()) {
          violations.add(new Violation("amount", "explicit null not allowed"));
        } else {
          if (!field.isNumber()) {
            violations.add(new Violation("amount", "expected number"));
          } else {
            amount = field.doubleValue();
          }
        }
      }
      String note = null;
      {
        JsonNode field = node.get("note");
        if (field == null) {
          violations.add(new Violation("note", "required"));
        } else if (field.isNull()) {
          violations.add(new Violation("note", "explicit null not allowed"));
        } else {
          if (!field.isTextual()) {
            violations.add(new Violation("note", "expected string"));
          } else {
            note = field.textValue();
          }
        }
      }
      if (!violations.isEmpty()) {
        throw new ValidationException(violations);
      }
      return new AttachApprovalContextInput(itemId, requester, amount, note);
    }
  }
}
