// Generated by nex-gen. DO NOT EDIT.
package io.temporal.samples.nexuswalkthrough.generatedservice;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

@JsonSerialize(using = CheckApprovalRequiredOutput.Serializer.class)
@JsonDeserialize(using = CheckApprovalRequiredOutput.Deserializer.class)
public final class CheckApprovalRequiredOutput {
  /** Whether an approval has to be started. */
  private final boolean approvalRequired;

  /** The spend threshold that was applied. */
  private final double threshold;

  public CheckApprovalRequiredOutput(boolean approvalRequired, double threshold) {
    this.approvalRequired = approvalRequired;
    this.threshold = threshold;
  }

  public boolean getApprovalRequired() {
    return approvalRequired;
  }

  public double getThreshold() {
    return threshold;
  }

  @Override
  public boolean equals(@Nullable Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof CheckApprovalRequiredOutput)) {
      return false;
    }
    CheckApprovalRequiredOutput that = (CheckApprovalRequiredOutput) other;
    return this.approvalRequired == that.approvalRequired && this.threshold == that.threshold;
  }

  @Override
  public int hashCode() {
    return Objects.hash(approvalRequired, threshold);
  }

  @Override
  public String toString() {
    return "CheckApprovalRequiredOutput{"
        + "approvalRequired="
        + approvalRequired
        + ", threshold="
        + threshold
        + "}";
  }

  public static final class Serializer
      extends com.fasterxml.jackson.databind.JsonSerializer<CheckApprovalRequiredOutput> {
    @Override
    public void serialize(
        CheckApprovalRequiredOutput value, JsonGenerator gen, SerializerProvider serializers)
        throws IOException {
      gen.writeStartObject();
      gen.writeBooleanField("approvalRequired", value.approvalRequired);

      gen.writeNumberField("threshold", value.threshold);

      gen.writeEndObject();
    }
  }

  public static final class Deserializer
      extends com.fasterxml.jackson.databind.JsonDeserializer<CheckApprovalRequiredOutput> {
    @Override
    public CheckApprovalRequiredOutput deserialize(
        JsonParser parser, DeserializationContext context) throws IOException {
      JsonNode node = parser.readValueAsTree();
      List<Violation> violations = new ArrayList<>();
      if (node == null || !node.isObject()) {
        violations.add(new Violation("", "expected object"));
        throw new ValidationException(violations);
      }
      Iterator<String> fieldNames = node.fieldNames();
      while (fieldNames.hasNext()) {
        String key = fieldNames.next();
        switch (key) {
          case "approvalRequired":
          case "threshold":
            break;
          default:
            violations.add(new Violation(key, "unknown field"));
        }
      }
      boolean approvalRequired = false;
      {
        JsonNode field = node.get("approvalRequired");
        if (field == null) {
          violations.add(new Violation("approvalRequired", "required"));
        } else if (field.isNull()) {
          violations.add(new Violation("approvalRequired", "explicit null not allowed"));
        } else {
          if (!field.isBoolean()) {
            violations.add(new Violation("approvalRequired", "expected boolean"));
          } else {
            approvalRequired = field.booleanValue();
          }
        }
      }
      double threshold = 0.0;
      {
        JsonNode field = node.get("threshold");
        if (field == null) {
          violations.add(new Violation("threshold", "required"));
        } else if (field.isNull()) {
          violations.add(new Violation("threshold", "explicit null not allowed"));
        } else {
          if (!field.isNumber()) {
            violations.add(new Violation("threshold", "expected number"));
          } else {
            threshold = field.doubleValue();
          }
        }
      }
      if (!violations.isEmpty()) {
        throw new ValidationException(violations);
      }
      return new CheckApprovalRequiredOutput(approvalRequired, threshold);
    }
  }
}
