// Generated by nex-gen. DO NOT EDIT.
package io.temporal.samples.nexuswalkthrough.generatedservice;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

@JsonSerialize(using = NotifyRequesterInput.Serializer.class)
@JsonDeserialize(using = NotifyRequesterInput.Deserializer.class)
public final class NotifyRequesterInput {
  public static final class Decision {
    public static final Decision DECISION_APPROVED = new Decision("APPROVED");
    public static final Decision DECISION_DENIED = new Decision("DENIED");

    private final String value;

    private Decision(String value) {
      this.value = value;
    }

    @JsonCreator
    public static @Nullable Decision fromString(String value) {
      if (value == null) {
        return null;
      }
      if ("APPROVED".equals(value)) {
        return DECISION_APPROVED;
      }
      if ("DENIED".equals(value)) {
        return DECISION_DENIED;
      }
      throw new IllegalArgumentException(
          "must be one of [\"APPROVED\", \"DENIED\"], got \"" + value + "\"");
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public boolean equals(@Nullable Object other) {
      if (this == other) {
        return true;
      }
      if (!(other instanceof Decision)) {
        return false;
      }
      Decision that = (Decision) other;
      return Objects.equals(this.value, that.value);
    }

    @Override
    public int hashCode() {
      return Objects.hash(value);
    }

    @Override
    public String toString() {
      return "Decision[" + value + "]";
    }
  }

  private final String requester;

  /** The final decision. */
  private final Decision decision;

  public NotifyRequesterInput(String requester, Decision decision) {
    this.requester = requester;
    this.decision = decision;
  }

  public String getRequester() {
    return requester;
  }

  public Decision getDecision() {
    return decision;
  }

  @Override
  public boolean equals(@Nullable Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof NotifyRequesterInput)) {
      return false;
    }
    NotifyRequesterInput that = (NotifyRequesterInput) other;
    return Objects.equals(this.requester, that.requester)
        && Objects.equals(this.decision, that.decision);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requester, decision);
  }

  @Override
  public String toString() {
    return "NotifyRequesterInput{" + "requester=" + requester + ", decision=" + decision + "}";
  }

  public static final class Serializer
      extends com.fasterxml.jackson.databind.JsonSerializer<NotifyRequesterInput> {
    @Override
    public void serialize(
        NotifyRequesterInput value, JsonGenerator gen, SerializerProvider serializers)
        throws IOException {
      gen.writeStartObject();
      if (value.requester != null) {
        gen.writeStringField("requester", value.requester);
      }
      if (value.decision != null) {
        gen.writeStringField("decision", value.decision.getValue());
      }
      gen.writeEndObject();
    }
  }

  public static final class Deserializer
      extends com.fasterxml.jackson.databind.JsonDeserializer<NotifyRequesterInput> {
    @Override
    public NotifyRequesterInput deserialize(JsonParser parser, DeserializationContext context)
        throws IOException {
      JsonNode node = parser.readValueAsTree();
      List<Violation> violations = new ArrayList<>();
      if (node == null || !node.isObject()) {
        violations.add(new Violation("", "expected object"));
        throw new ValidationException(violations);
      }
      Iterator<String> fieldNames = node.fieldNames();
      while (fieldNames.hasNext()) {
        String key = fieldNames.next();
        switch (key) {
          case "decision":
          case "requester":
            break;
          default:
            violations.add(new Violation(key, "unknown field"));
        }
      }
      String requester = null;
      {
        JsonNode field = node.get("requester");
        if (field == null) {
          violations.add(new Violation("requester", "required"));
        } else if (field.isNull()) {
          violations.add(new Violation("requester", "explicit null not allowed"));
        } else {
          if (!field.isTextual()) {
            violations.add(new Violation("requester", "expected string"));
          } else {
            requester = field.textValue();
          }
        }
      }
      Decision decision = null;
      {
        JsonNode field = node.get("decision");
        if (field == null) {
          violations.add(new Violation("decision", "required"));
        } else if (field.isNull()) {
          violations.add(new Violation("decision", "explicit null not allowed"));
        } else {
          if (!field.isTextual()) {
            violations.add(new Violation("decision", "expected string"));
          } else {
            String decisionValue = field.textValue();
            if ("APPROVED".equals(decisionValue)) {
              decision = Decision.DECISION_APPROVED;
            } else if ("DENIED".equals(decisionValue)) {
              decision = Decision.DECISION_DENIED;
            } else {
              violations.add(
                  new Violation(
                      "decision",
                      "must be one of [\"APPROVED\", \"DENIED\"], got " + decisionValue));
            }
          }
        }
      }
      if (!violations.isEmpty()) {
        throw new ValidationException(violations);
      }
      return new NotifyRequesterInput(requester, decision);
    }
  }
}
