// Generated by nex-gen. DO NOT EDIT.
package io.temporal.samples.nexuswalkthrough.generatedservice;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

@JsonSerialize(using = NotifyRequesterOutput.Serializer.class)
@JsonDeserialize(using = NotifyRequesterOutput.Deserializer.class)
public final class NotifyRequesterOutput {
  /** Where the notification was sent. */
  private final String deliveredTo;

  public NotifyRequesterOutput(String deliveredTo) {
    this.deliveredTo = deliveredTo;
  }

  public String getDeliveredTo() {
    return deliveredTo;
  }

  @Override
  public boolean equals(@Nullable Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof NotifyRequesterOutput)) {
      return false;
    }
    NotifyRequesterOutput that = (NotifyRequesterOutput) other;
    return Objects.equals(this.deliveredTo, that.deliveredTo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveredTo);
  }

  @Override
  public String toString() {
    return "NotifyRequesterOutput{" + "deliveredTo=" + deliveredTo + "}";
  }

  public static final class Serializer
      extends com.fasterxml.jackson.databind.JsonSerializer<NotifyRequesterOutput> {
    @Override
    public void serialize(
        NotifyRequesterOutput value, JsonGenerator gen, SerializerProvider serializers)
        throws IOException {
      gen.writeStartObject();
      if (value.deliveredTo != null) {
        gen.writeStringField("deliveredTo", value.deliveredTo);
      }
      gen.writeEndObject();
    }
  }

  public static final class Deserializer
      extends com.fasterxml.jackson.databind.JsonDeserializer<NotifyRequesterOutput> {
    @Override
    public NotifyRequesterOutput deserialize(JsonParser parser, DeserializationContext context)
        throws IOException {
      JsonNode node = parser.readValueAsTree();
      List<Violation> violations = new ArrayList<>();
      if (node == null || !node.isObject()) {
        violations.add(new Violation("", "expected object"));
        throw new ValidationException(violations);
      }
      Iterator<String> fieldNames = node.fieldNames();
      while (fieldNames.hasNext()) {
        String key = fieldNames.next();
        switch (key) {
          case "deliveredTo":
            break;
          default:
            violations.add(new Violation(key, "unknown field"));
        }
      }
      String deliveredTo = null;
      {
        JsonNode field = node.get("deliveredTo");
        if (field == null) {
          violations.add(new Violation("deliveredTo", "required"));
        } else if (field.isNull()) {
          violations.add(new Violation("deliveredTo", "explicit null not allowed"));
        } else {
          if (!field.isTextual()) {
            violations.add(new Violation("deliveredTo", "expected string"));
          } else {
            deliveredTo = field.textValue();
          }
        }
      }
      if (!violations.isEmpty()) {
        throw new ValidationException(violations);
      }
      return new NotifyRequesterOutput(deliveredTo);
    }
  }
}
