// Generated by nex-gen. DO NOT EDIT.
package io.temporal.samples.nexuswalkthrough.generatedservice;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

@JsonSerialize(using = RemindApproverInput.Serializer.class)
@JsonDeserialize(using = RemindApproverInput.Deserializer.class)
public final class RemindApproverInput {
  private final String itemId;

  public RemindApproverInput(String itemId) {
    this.itemId = itemId;
  }

  public String getItemId() {
    return itemId;
  }

  @Override
  public boolean equals(@Nullable Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof RemindApproverInput)) {
      return false;
    }
    RemindApproverInput that = (RemindApproverInput) other;
    return Objects.equals(this.itemId, that.itemId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemId);
  }

  @Override
  public String toString() {
    return "RemindApproverInput{" + "itemId=" + itemId + "}";
  }

  public static final class Serializer
      extends com.fasterxml.jackson.databind.JsonSerializer<RemindApproverInput> {
    @Override
    public void serialize(
        RemindApproverInput value, JsonGenerator gen, SerializerProvider serializers)
        throws IOException {
      gen.writeStartObject();
      if (value.itemId != null) {
        gen.writeStringField("itemId", value.itemId);
      }
      gen.writeEndObject();
    }
  }

  public static final class Deserializer
      extends com.fasterxml.jackson.databind.JsonDeserializer<RemindApproverInput> {
    @Override
    public RemindApproverInput deserialize(JsonParser parser, DeserializationContext context)
        throws IOException {
      JsonNode node = parser.readValueAsTree();
      List<Violation> violations = new ArrayList<>();
      if (node == null || !node.isObject()) {
        violations.add(new Violation("", "expected object"));
        throw new ValidationException(violations);
      }
      Iterator<String> fieldNames = node.fieldNames();
      while (fieldNames.hasNext()) {
        String key = fieldNames.next();
        switch (key) {
          case "itemId":
            break;
          default:
            violations.add(new Violation(key, "unknown field"));
        }
      }
      String itemId = null;
      {
        JsonNode field = node.get("itemId");
        if (field == null) {
          violations.add(new Violation("itemId", "required"));
        } else if (field.isNull()) {
          violations.add(new Violation("itemId", "explicit null not allowed"));
        } else {
          if (!field.isTextual()) {
            violations.add(new Violation("itemId", "expected string"));
          } else {
            itemId = field.textValue();
          }
        }
      }
      if (!violations.isEmpty()) {
        throw new ValidationException(violations);
      }
      return new RemindApproverInput(itemId);
    }
  }
}
