// Generated by nex-gen. DO NOT EDIT.
package io.temporal.samples.nexuswalkthrough.generatedservice;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Shared spec-number parsing enforcing the JSON Schema integer semantics. */
public final class SpecNumbers {
  public static final long INTEGER_CAP = (1L << 53) - 1;

  private SpecNumbers() {}

  /**
   * Parses a JSON number as a spec integer: rejects non-numbers, fractional values, and magnitudes
   * beyond the +/-(2^53-1) cap. Adds a {@link Violation} and returns {@code null} on failure.
   */
  public static @Nullable Long specLong(JsonNode node, String path, List<Violation> violations) {
    if (!node.isNumber()) {
      violations.add(new Violation(path, "expected integer"));
      return null;
    }
    double value = node.doubleValue();
    if (Double.isNaN(value) || Double.isInfinite(value) || value != Math.floor(value)) {
      violations.add(new Violation(path, "not an integer"));
      return null;
    }
    if (value < -(double) INTEGER_CAP || value > (double) INTEGER_CAP) {
      violations.add(new Violation(path, "exceeds \u00b1(2^53-1) integer cap"));
      return null;
    }
    return node.longValue();
  }
}
