// Generated by nex-gen. DO NOT EDIT.
package io.temporal.samples.nexuswalkthrough.generatedservice;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

@JsonSerialize(using = SubmitDecisionOutput.Serializer.class)
@JsonDeserialize(using = SubmitDecisionOutput.Deserializer.class)
public final class SubmitDecisionOutput {
  public static final class Recorded {
    public static final Recorded RECORDED_APPROVED = new Recorded("APPROVED");
    public static final Recorded RECORDED_DENIED = new Recorded("DENIED");

    private final String value;

    private Recorded(String value) {
      this.value = value;
    }

    @JsonCreator
    public static @Nullable Recorded fromString(String value) {
      if (value == null) {
        return null;
      }
      if ("APPROVED".equals(value)) {
        return RECORDED_APPROVED;
      }
      if ("DENIED".equals(value)) {
        return RECORDED_DENIED;
      }
      throw new IllegalArgumentException(
          "must be one of [\"APPROVED\", \"DENIED\"], got \"" + value + "\"");
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public boolean equals(@Nullable Object other) {
      if (this == other) {
        return true;
      }
      if (!(other instanceof Recorded)) {
        return false;
      }
      Recorded that = (Recorded) other;
      return Objects.equals(this.value, that.value);
    }

    @Override
    public int hashCode() {
      return Objects.hash(value);
    }

    @Override
    public String toString() {
      return "Recorded[" + value + "]";
    }
  }

  /** The decision that was recorded. */
  private final Recorded recorded;

  /** How many reminders were sent before the decision. */
  private final long remindersSent;

  public SubmitDecisionOutput(Recorded recorded, long remindersSent) {
    this.recorded = recorded;
    this.remindersSent = remindersSent;
  }

  public Recorded getRecorded() {
    return recorded;
  }

  public long getRemindersSent() {
    return remindersSent;
  }

  @Override
  public boolean equals(@Nullable Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof SubmitDecisionOutput)) {
      return false;
    }
    SubmitDecisionOutput that = (SubmitDecisionOutput) other;
    return Objects.equals(this.recorded, that.recorded) && this.remindersSent == that.remindersSent;
  }

  @Override
  public int hashCode() {
    return Objects.hash(recorded, remindersSent);
  }

  @Override
  public String toString() {
    return "SubmitDecisionOutput{"
        + "recorded="
        + recorded
        + ", remindersSent="
        + remindersSent
        + "}";
  }

  public static final class Serializer
      extends com.fasterxml.jackson.databind.JsonSerializer<SubmitDecisionOutput> {
    @Override
    public void serialize(
        SubmitDecisionOutput value, JsonGenerator gen, SerializerProvider serializers)
        throws IOException {
      gen.writeStartObject();
      if (value.recorded != null) {
        gen.writeStringField("recorded", value.recorded.getValue());
      }
      gen.writeNumberField("remindersSent", value.remindersSent);

      gen.writeEndObject();
    }
  }

  public static final class Deserializer
      extends com.fasterxml.jackson.databind.JsonDeserializer<SubmitDecisionOutput> {
    @Override
    public SubmitDecisionOutput deserialize(JsonParser parser, DeserializationContext context)
        throws IOException {
      JsonNode node = parser.readValueAsTree();
      List<Violation> violations = new ArrayList<>();
      if (node == null || !node.isObject()) {
        violations.add(new Violation("", "expected object"));
        throw new ValidationException(violations);
      }
      Iterator<String> fieldNames = node.fieldNames();
      while (fieldNames.hasNext()) {
        String key = fieldNames.next();
        switch (key) {
          case "recorded":
          case "remindersSent":
            break;
          default:
            violations.add(new Violation(key, "unknown field"));
        }
      }
      Recorded recorded = null;
      {
        JsonNode field = node.get("recorded");
        if (field == null) {
          violations.add(new Violation("recorded", "required"));
        } else if (field.isNull()) {
          violations.add(new Violation("recorded", "explicit null not allowed"));
        } else {
          if (!field.isTextual()) {
            violations.add(new Violation("recorded", "expected string"));
          } else {
            String recordedValue = field.textValue();
            if ("APPROVED".equals(recordedValue)) {
              recorded = Recorded.RECORDED_APPROVED;
            } else if ("DENIED".equals(recordedValue)) {
              recorded = Recorded.RECORDED_DENIED;
            } else {
              violations.add(
                  new Violation(
                      "recorded",
                      "must be one of [\"APPROVED\", \"DENIED\"], got " + recordedValue));
            }
          }
        }
      }
      long remindersSent = 0L;
      {
        JsonNode field = node.get("remindersSent");
        if (field == null) {
          violations.add(new Violation("remindersSent", "required"));
        } else if (field.isNull()) {
          violations.add(new Violation("remindersSent", "explicit null not allowed"));
        } else {
          Long numberValue = SpecNumbers.specLong(field, "remindersSent", violations);
          if (numberValue != null) {
            remindersSent = numberValue;
          }
        }
      }
      if (!violations.isEmpty()) {
        throw new ValidationException(violations);
      }
      return new SubmitDecisionOutput(recorded, remindersSent);
    }
  }
}
