// Generated by nex-gen. DO NOT EDIT.
package io.temporal.samples.nexuswalkthrough.generatedservice;

import com.fasterxml.jackson.databind.JsonMappingException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/** Aggregates every {@link Violation} found while (de)serializing a value. */
public final class ValidationException extends JsonMappingException {
  private final List<Violation> violations;

  public ValidationException(List<Violation> violations) {
    super((java.io.Closeable) null, buildMessage(violations));
    this.violations = Collections.unmodifiableList(new ArrayList<>(violations));
  }

  public List<Violation> getViolations() {
    return violations;
  }

  private static String buildMessage(List<Violation> violations) {
    StringBuilder builder = new StringBuilder();
    builder.append(violations.size()).append(" validation error(s): ");
    for (int index = 0; index < violations.size(); index++) {
      if (index > 0) {
        builder.append("; ");
      }
      builder.append(violations.get(index).toString());
    }
    return builder.toString();
  }
}
