// Generated by nex-gen. DO NOT EDIT.
package io.temporal.samples.nexuswalkthrough.generatedservice;

import org.jspecify.annotations.Nullable;

/** A single constraint failure: a JSON member path and a human-readable reason. */
public final class Violation {
  private final String path;
  private final String reason;

  public Violation(String path, String reason) {
    this.path = path;
    this.reason = reason;
  }

  public String getPath() {
    return path;
  }

  public String getReason() {
    return reason;
  }

  public Violation withPathPrefix(String prefix) {
    if (path == null || path.isEmpty()) {
      return new Violation(prefix, reason);
    }
    return new Violation(prefix + "." + path, reason);
  }

  @Override
  public String toString() {
    if (path == null || path.isEmpty()) {
      return reason;
    }
    return path + ": " + reason;
  }

  @Override
  public boolean equals(@Nullable Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof Violation)) {
      return false;
    }
    Violation that = (Violation) other;
    return java.util.Objects.equals(path, that.path)
        && java.util.Objects.equals(reason, that.reason);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(path, reason);
  }
}
